### ISSUE TITLE
Not working on Android Devices

### ISSUE THREAD

**Issue by sporteman** [expo/audio-recording-example#11]
When I try to record an audio I got:

```
[01:01:33] [Unhandled promise rejection: Error: Start encountered an error: recording not started]
- node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:121:42 in createErrorFromErrorData
- node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:78:57 in <unknown>
- ... 5 more stack frames from framework internals
```

**Comment by AdrianDroid** [comment]
+1

**Comment by AdrianDroid** [comment]
+1
Doc is a mess 
and now the example too?

**Comment by aaronwilly** [comment]
Yes, never working

**Comment by metavaults** [comment]
What about the Sound REcording for Android, guys?? Why it's not working yet?

**Comment by cruzach** [comment]
Hey, I've just updated this example repo to SDK 34 so lmk if it still doesn't work. If you have issues with Expo's Audio API, then it's best to file issues at the [main Expo repo](https://github.com/expo/expo/issues)
