### ISSUE TITLE
Audio on Android emulator is distorted

### ISSUE THREAD

**Issue by audiobeing** [expo/audio-recording-example#17]
Hi there, 
Not 100% sure this is the right place to post this. 
When I record and playback audio on the android emulator - the sound is heavily distorted. I am using the code as is. On ios, everything works fine.

**Comment by tesmojones** [comment]
i am having this issue also

**Comment by IjzerenHein** [comment]
You should not expect audio recordings on the emulator to have the same level of quality as on a real device. Instead, see it as a development platform only. Please test audio recordings on a real device. If you run into problems please report them to the [main Expo repository](https://github.com/expo/expo/issues) 👍
