### ISSUE TITLE
Not working on iOS device

### ISSUE THREAD

**Issue by mayu-496** [expo/audio-recording-example#18]
I'm trying to run this code on iphone but it is not working.. when i press Start every thing gets disabled.. It doesn't even start recording..

**Comment by lankinenxyz** [comment]
Check this [https://github.com/expo/expo/issues/5801](https://github.com/expo/expo/issues/5801). You need to use a real device and not Xcode's simulator. It at least solved the problem for me.

**Comment by IjzerenHein** [comment]
You'll indeed need to use a real device to record audio. When you press the microphone it will toggle the recording on and off. 👍
