### ISSUE TITLE
TypeError: recording.setOnRecordingStatusUpdate is not a function. 

### ISSUE THREAD

**Issue by jswhisperer** [expo/audio-recording-example#3]
Tested on iPhone 6, iPhone simulator, OnePlus 5 Android

All the same error

audio-recording-example: npm -v
3.8.6
audio-recording-example: node -v
v6.0.0

`Possible Unhandled Promise Rejection (id: 0):
TypeError: recording.setOnRecordingStatusUpdate is not a function. (In 'recording.setOnRecordingStatusUpdate(this._updateScreenForRecordingStatus)', 'recording.setOnRecordingStatusUpdate' is undefined)
_stopPlaybackAndBeginRecording$@http://packager.5p-j8c.gregbenner.audio-recording-example.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=expo/tools/hashAssetFiles:1571:51
tryCatch@http://packager.5p-j8c.gregbenner.audio-recording-example.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=expo/tools/hashAssetFiles:15620:44
invoke@http://packager.5p-j8c.gregbenner.audio-recording-example.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=expo/tools/hashAssetFiles:15808:30
tryCatch@http://packager.5p-j8c.gregbenner.audio-recording-example.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=expo/tools/hashAssetFiles:15620:44
invoke@http://packager.5p-j8c.gregbenner.audio-recording-example.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=expo/tools/hashAssetFiles:15678:28
http://packager.5p-j8c.gregbenner.audio-recording-example.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=expo/tools/hashAssetFiles:15686:19
tryCallOne@http://packager.5p-j8c.gregbenner.audio-recording-example.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=expo/tools/hashAssetFiles:14976:14
http://packager.5p-j8c.gregbenner.audio-recording-example.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=expo/tools/hashAssetFiles:15062:25
callTimer@http://packager.5p-j8c.gregbenner.audio-recording-example.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=expo/tools/hashAssetFiles:5945:17
callImmediatesPass@http://packager.5p-j8c.gregbenner.audio-recording-example.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=expo/tools/hashAssetFiles:6034:36
callImmediates@http://packager.5p-j8c.gregbenner.audio-recording-example.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=expo/tools/hashAssetFiles:6045:48
__callImmediates@http://packager.5p-j8c.gregbenner.audio-recording-example.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=expo/tools/hashAssetFiles:5813:39
http://packager.5p-j8c.gregbenner.audio-recording-example.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=expo/tools/hashAssetFiles:5703:32
__guard@http://packager.5p-j8c.gregbenner.audio-recording-example.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=expo/tools/hashAssetFiles:5802:11
flushedQueue@http://packager.5p-j8c.gregbenner.audio-recording-example.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=expo/tools/hashAssetFiles:5702:19
flushedQueue@[native code]
invokeCallbackAndReturnFlushedQueue@[native code]

GNB-Pro
`

**Comment by jswhisperer** [comment]
Hosted here also https://expo.io/@gregbenner/record just the stock packages that package.json references

**Comment by ccheever** [comment]
Hi! Sorry about this. Someone just fixed the example. I'm not sure how it got into a broken state. It works now, but let know if it doesn't work for you.

**Comment by jswhisperer** [comment]
Thank you kindly! Works great now :)
