### ISSUE TITLE
Unnecessary JSON processing

### ISSUE THREAD

**Issue by ghost** [expo/audio-recording-example#6]
Nit Pick: [Line 69](https://github.com/expo/audio-recording-example/blob/master/App.js#L69) of App.js stringifies an object and then immediately parses it again, leaving you with the original object.

    this.recordingSettings = JSON.parse(JSON.stringify(Audio.RECORDING_OPTIONS_PRESET_LOW_QUALITY));

I think this can be simplified to

    this.recordingSettings = Audio.RECORDING_OPTIONS_PRESET_LOW_QUALITY;

**Comment by fxfactorial** [comment]
It might have been a desire to copy the object
