### ISSUE TITLE
Needs update on expo.io

### ISSUE THREAD

**Issue by heyakyra** [expo/audio-recording-example#8]
Being the [reference example](https://docs.expo.io/versions/latest/sdk/audio.html) of a recording app in the expo docs, it should probably work: https://expo.io/@community/record 

Instead, it says: 

> ## This project needs an update
> 
> This project uses Expo SDK v16.0.0. If you want to open this project, the author will need to update the project's SDK version.

**Comment by cruzach** [comment]
Fixed here -> https://github.com/expo/expo/pull/5153

Thanks for pointing this out
