### ISSUE TITLE
Add comment for JSON.parse/JSON.stringify

### ISSUE THREAD

**Issue by spedy** [expo/audio-recording-example#9]
Can you please add a comment why JSON stringify and parsing is required [here](https://github.com/expo/audio-recording-example/blob/master/App.js#L69)?

**Comment by IjzerenHein** [comment]
That was done only to prevent modification of the default preset object. The code was indeed a bit vague on this.
I've updated it so that it should be clearer to the reader 👍 
https://github.com/expo/audio-recording-example/blob/master/App.tsx#L71-L80
